<?php $pageTitle = $pageTitle ?? 'Job Fair Report'; ?>
<?php ob_start(); ?>

<style>
@media print { .no-print { display:none!important; } @page { size: A4; margin: 10mm; } }
</style>

<div class="no-print d-flex gap-2 mb-4 flex-wrap align-items-center">
    <a href="<?= APP_URL ?>/reporting-officer/dashboard" class="btn btn-outline-secondary btn-sm">
        <i class="bi bi-arrow-left me-1"></i>Dashboard
    </a>
    <a href="<?= APP_URL ?>/reporting-officer/reports" class="btn btn-outline-primary btn-sm">
        <i class="bi bi-archive me-1"></i>All Reports
    </a>
    <?php
    // Check if a saved report exists for this fair
    $db = Database::getInstance();
    $savedReport = $db->fetch(
        "SELECT id, report_status, generated_at FROM job_fair_reports WHERE job_fair_request_id = ?",
        [$fair['id']]
    );
    ?>
    <?php if ($savedReport): ?>
    <span class="badge bg-<?= ['draft'=>'secondary','submitted'=>'primary','reviewed'=>'success'][$savedReport['report_status']] ?> py-2 px-3">
        <?= ucfirst($savedReport['report_status']) ?>
        — Generated <?= date('M d, Y', strtotime($savedReport['generated_at'])) ?>
    </span>
    <?php if ($savedReport['report_status'] === 'draft'): ?>
    <button type="button"
            class="btn btn-primary btn-sm"
            data-bs-toggle="modal"
            data-bs-target="#submitFromFairModal"
            data-reportid="<?= $savedReport['id'] ?>">
        <i class="bi bi-send me-1"></i>Send to Supervising Labor
    </button>
    <a href="<?= APP_URL ?>/reporting-officer/reports/<?= $savedReport['id'] ?>/view"
       class="btn btn-outline-success btn-sm">
        <i class="bi bi-eye me-1"></i>View Saved Report
    </a>
    <?php endif; ?>
    <?php endif; ?>
    <button type="button" class="btn btn-success btn-sm <?= $savedReport ? 'ms-0' : '' ?>"
            data-bs-toggle="collapse" data-bs-target="#generateForm">
        <i class="bi bi-file-earmark-bar-graph me-1"></i>Generate Summary Report
    </button>
    <button onclick="window.print()" class="btn btn-outline-dark btn-sm ms-auto">
        <i class="bi bi-printer me-1"></i>Print
    </button>
</div>

<!-- Generate Report Form (collapsible) -->
<div class="collapse mb-4" id="generateForm">
    <div class="card border-success shadow-sm">
        <div class="card-header bg-success text-white py-2">
            <h6 class="mb-0 small fw-bold"><i class="bi bi-file-earmark-bar-graph me-2"></i>Generate Summary Report</h6>
        </div>
        <div class="card-body">
            <form method="POST" action="<?= APP_URL ?>/reporting-officer/generate-report/<?= $fair['id'] ?>">
                <?= csrfField() ?>
                <div class="row g-3">
                    <div class="col-12">
                        <label class="form-label fw-semibold small">Overall Assessment <span class="text-muted">(optional)</span></label>
                        <textarea name="overall_remarks" class="form-control form-control-sm" rows="3"
                                  placeholder="Overall assessment of the job fair outcome..."
                        ><?= htmlspecialchars($savedReport ? ($db->fetch("SELECT overall_remarks FROM job_fair_reports WHERE id=?",[$savedReport['id']])['overall_remarks'] ?? '') : '', ENT_QUOTES) ?></textarea>
                    </div>
                    <div class="col-md-6">
                        <label class="form-label fw-semibold small">Observations</label>
                        <textarea name="observations" class="form-control form-control-sm" rows="3"
                                  placeholder="Key observations from the job fair..."></textarea>
                    </div>
                    <div class="col-md-6">
                        <label class="form-label fw-semibold small">Recommendations &amp; Issues</label>
                        <textarea name="recommendations" class="form-control form-control-sm" rows="3"
                                  placeholder="Recommendations and suggested improvements..."></textarea>
                    </div>
                    <div class="col-12">
                        <button type="submit" class="btn btn-success btn-sm">
                            <i class="bi bi-bar-chart-fill me-1"></i>Generate &amp; Save Report
                        </button>
                        <button type="button" class="btn btn-outline-secondary btn-sm ms-2"
                                data-bs-toggle="collapse" data-bs-target="#generateForm">Cancel</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Report Header -->
<div class="card border-0 shadow-sm mb-4">
    <div class="card-header bg-dark text-white text-center py-3">
        <h5 class="mb-1 fw-bold">JOB FAIR REPORT</h5>
        <p class="mb-0 small opacity-75">Generated by Reporting Officer</p>
    </div>
    <div class="card-body">
        <div class="row g-3">
            <div class="col-md-6">
                <div class="small text-muted">Job Fair Title</div>
                <div class="fw-bold"><?= htmlspecialchars($fair['title'], ENT_QUOTES) ?></div>
            </div>
            <div class="col-md-3">
                <div class="small text-muted">Date</div>
                <div class="fw-bold"><?= !empty($fair['requested_date']) ? date('F d, Y', strtotime($fair['requested_date'])) : '—' ?></div>
            </div>
            <div class="col-md-3">
                <div class="small text-muted">Venue</div>
                <div class="fw-bold"><?= htmlspecialchars($fair['venue'] ?? '—', ENT_QUOTES) ?></div>
            </div>
        </div>
    </div>
</div>

<!-- Summary Stats -->
<div class="row g-3 mb-4">
    <?php
    $cards = [
        ['Applicants Participated', $summary['total_applicants'],  'secondary', 'bi-people'],
        ['Validated',               $summary['total_validated'],   'info',      'bi-patch-check-fill'],
        ['Interviewed',             $summary['total_interviewed'], 'warning',   'bi-camera-video-fill'],
        ['Hired',                   $summary['total_hired'],       'success',   'bi-person-check-fill'],
        ['Not Hired',               $summary['total_not_hired'],   'danger',    'bi-person-x-fill'],
        ['Agencies',                $summary['total_agencies'],    'primary',   'bi-building'],
        ['Vacancies Offered',       $summary['total_vacancies'],   'primary',   'bi-briefcase-fill'],
        ['Employment Rate',         $summary['employment_rate'].'%','success',  'bi-graph-up-arrow'],
    ];
    foreach ($cards as [$label, $val, $color, $icon]): ?>
    <div class="col-6 col-sm-3">
        <div class="card border-0 shadow-sm text-center py-3 h-100">
            <div class="fw-bold" style="font-size:1.8rem;color:var(--bs-<?= $color ?>);"><?= $val ?></div>
            <div class="small text-muted mt-1"><?= $label ?></div>
        </div>
    </div>
    <?php endforeach; ?>
</div>

<!-- Agency Performance Table -->
<div class="card border-0 shadow-sm mb-4">
    <div class="card-header bg-white py-3">
        <h6 class="mb-0 fw-bold"><i class="bi bi-building me-2 text-primary"></i>Agency Performance</h6>
    </div>
    <div class="table-responsive">
        <table class="table table-sm table-bordered align-middle mb-0">
            <thead class="table-dark">
                <tr>
                    <th>#</th>
                    <th>Agency / Company</th>
                    <th class="text-center">Vacancies</th>
                    <th class="text-center">Total Slots</th>
                    <th class="text-center">Interviewed</th>
                    <th class="text-center">Hired</th>
                    <th class="text-center">Not Hired</th>
                    <th class="text-center">Hire Rate</th>
                </tr>
            </thead>
            <tbody>
            <?php if (empty($agencies)): ?>
                <tr><td colspan="8" class="text-center py-3 text-muted">No agencies yet.</td></tr>
            <?php else: ?>
            <?php foreach ($agencies as $i => $ag):
                $rate = $ag['interviewed_count'] > 0
                    ? round(($ag['hired_count'] / $ag['interviewed_count']) * 100, 0) : 0;
            ?>
            <tr>
                <td class="text-muted"><?= $i + 1 ?></td>
                <td class="fw-semibold"><?= htmlspecialchars($ag['agency_name'], ENT_QUOTES) ?></td>
                <td class="text-center"><?= $ag['vacancy_count'] ?></td>
                <td class="text-center"><?= $ag['total_slots'] ?? 0 ?></td>
                <td class="text-center"><span class="badge bg-info text-dark"><?= $ag['interviewed_count'] ?></span></td>
                <td class="text-center"><span class="badge bg-success"><?= $ag['hired_count'] ?></span></td>
                <td class="text-center"><span class="badge bg-danger"><?= $ag['not_hired_count'] ?></span></td>
                <td class="text-center">
                    <span class="badge bg-<?= $rate >= 50 ? 'success' : 'warning' ?> text-dark"><?= $rate ?>%</span>
                </td>
            </tr>
            <?php endforeach; ?>
            <?php endif; ?>
            </tbody>
        </table>
    </div>
</div>

<!-- Applicant Participation Table -->
<div class="card border-0 shadow-sm">
    <div class="card-header bg-white py-3 d-flex justify-content-between align-items-center">
        <h6 class="mb-0 fw-bold"><i class="bi bi-person-lines-fill me-2 text-success"></i>Applicant Participation (<?= count($applicants) ?>)</h6>
    </div>
    <div class="table-responsive">
        <table class="table table-sm table-bordered align-middle mb-0">
            <thead class="table-dark">
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Preferred Position</th>
                    <th class="text-center">Validated</th>
                    <th>Interviewed By</th>
                    <th class="text-center">Interview Status</th>
                    <th class="text-center">Outcome</th>
                    <th>Remarks</th>
                    <th class="no-print">Action</th>
                </tr>
            </thead>
            <tbody>
            <?php if (empty($applicants)): ?>
                <tr><td colspan="10" class="text-center py-4 text-muted">No applicant records yet.</td></tr>
            <?php else: ?>
            <?php foreach ($applicants as $i => $ap):
                $vsColors = ['approved'=>'success','pending'=>'warning','rejected'=>'danger','not_submitted'=>'secondary','resubmit'=>'info'];
                $vsColor  = $vsColors[$ap['validation_status']] ?? 'secondary';
                $oColors  = ['qualified_for_contact'=>'success','waitlisted'=>'info','not_qualified'=>'danger','pending'=>'warning'];
                $oColor   = $oColors[$ap['hiring_outcome'] ?? 'pending'] ?? 'secondary';
            ?>
            <tr>
                <td class="text-muted"><?= $i + 1 ?></td>
                <td class="fw-semibold small">
                    <?= htmlspecialchars(strtoupper($ap['surname']) . ', ' . $ap['firstname'], ENT_QUOTES) ?>
                </td>
                <td class="small text-muted"><?= htmlspecialchars($ap['email'] ?? '—', ENT_QUOTES) ?></td>
                <td class="small"><?= htmlspecialchars($ap['preferred_occupation'] ?? '—', ENT_QUOTES) ?></td>
                <td class="text-center">
                    <span class="badge bg-<?= $vsColor ?>"><?= ucfirst($ap['validation_status']) ?></span>
                </td>
                <td class="small"><?= htmlspecialchars($ap['interviewed_by'] ?? '—', ENT_QUOTES) ?></td>
                <td class="text-center">
                    <?php if ($ap['interview_status']): ?>
                    <span class="badge bg-<?= $ap['interview_status'] === 'completed' ? 'success' : 'warning' ?>">
                        <?= ucfirst($ap['interview_status']) ?>
                    </span>
                    <?php else: ?>
                    <span class="text-muted small">—</span>
                    <?php endif; ?>
                </td>
                <td class="text-center">
                    <?php if ($ap['interview_id']): ?>
                    <span class="badge bg-<?= $oColor ?>">
                        <?= ucfirst(str_replace('_', ' ', $ap['hiring_outcome'] ?? 'pending')) ?>
                    </span>
                    <?php else: ?>
                    <span class="text-muted small">—</span>
                    <?php endif; ?>
                </td>
                <td class="small text-muted">
                    <?= htmlspecialchars(substr($ap['overall_remarks'] ?? '', 0, 40), ENT_QUOTES) ?>
                    <?= strlen($ap['overall_remarks'] ?? '') > 40 ? '...' : '' ?>
                </td>
                <td class="no-print">
                    <?php if ($ap['interview_id']): ?>
                    <a href="<?= APP_URL ?>/reporting-officer/interview/<?= $ap['interview_id'] ?>"
                       class="btn btn-xs btn-outline-primary" style="padding:2px 8px;font-size:.72rem;">
                        <i class="bi bi-eye"></i>
                    </a>
                    <?php endif; ?>
                </td>
            </tr>
            <?php endforeach; ?>
            <?php endif; ?>
            </tbody>
        </table>
    </div>
</div>

<?php $content = ob_get_clean(); include VIEW_PATH . '/layouts/main.php'; ?>

<!-- Submit from Job Fair Report page Modal -->
<?php if (!empty($savedReport) && $savedReport['report_status'] === 'draft'): ?>
<div class="modal fade" id="submitFromFairModal" tabindex="-1" data-bs-backdrop="static">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header bg-primary text-white">
                <h5 class="modal-title fw-bold">
                    <i class="bi bi-send me-2"></i>Submit Report to Supervising Labor
                </h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button>
            </div>
            <form method="POST"
                  action="<?= APP_URL ?>/reporting-officer/reports/<?= $savedReport['id'] ?>/submit">
                <?= csrfField() ?>
                <div class="modal-body">
                    <div class="alert alert-primary d-flex gap-3 mb-3 py-2">
                        <i class="bi bi-file-earmark-bar-graph fs-4 flex-shrink-0 mt-1"></i>
                        <div class="small">
                            <strong><?= htmlspecialchars($fair['title'], ENT_QUOTES) ?></strong><br>
                            <span class="text-muted">
                                Once submitted, this report will be locked and visible to Supervising Labor.
                            </span>
                        </div>
                    </div>

                    <!-- Required Remarks -->
                    <div class="mb-3">
                        <label class="form-label fw-bold">
                            Overall Remarks <span class="text-danger">*</span>
                        </label>
                        <textarea name="submission_remarks"
                                  id="fairReportRemarks"
                                  class="form-control" rows="5"
                                  placeholder="Enter your overall assessment of this job fair's outcomes, key observations, and recommendations before submitting to Supervising Labor..."
                                  required
                                  minlength="10"><?= htmlspecialchars($savedReport['overall_remarks'] ?? '', ENT_QUOTES) ?></textarea>
                        <div class="form-text text-muted">
                            <i class="bi bi-info-circle me-1"></i>
                            Required — minimum 10 characters. Permanently saved and visible to Supervising Labor.
                        </div>
                    </div>
                    <div class="mb-3">
                        <label class="form-label fw-semibold small">Observations <span class="text-muted">(optional)</span></label>
                        <textarea name="submission_observations" class="form-control form-control-sm" rows="2"
                                  placeholder="Key observations from the job fair..."></textarea>
                    </div>
                    <div class="mb-0">
                        <label class="form-label fw-semibold small">Recommendations <span class="text-muted">(optional)</span></label>
                        <textarea name="submission_recommendations" class="form-control form-control-sm" rows="2"
                                  placeholder="Suggestions for future job fairs..."></textarea>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary fw-semibold px-4"
                            id="fairSubmitBtn"
                            <?= empty($savedReport['overall_remarks']) ? 'disabled' : '' ?>>
                        <i class="bi bi-send me-2"></i>Submit to Supervising Labor
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
document.getElementById('fairReportRemarks')?.addEventListener('input', function() {
    document.getElementById('fairSubmitBtn').disabled = this.value.trim().length < 10;
});
</script>
<?php endif; ?>
