<?php $pageTitle = $pageTitle ?? 'Job Fair Report'; ?>
<?php ob_start(); ?>

<style>
@media print { .no-print { display:none!important; } @page { size: A4; margin: 10mm; } }
</style>

<div class="no-print d-flex gap-2 mb-4 flex-wrap align-items-center">
    <a href="<?= APP_URL ?>/reporting-officer/dashboard" class="btn btn-outline-secondary btn-sm">
        <i class="bi bi-arrow-left me-1"></i>Dashboard
    </a>
    <form method="POST" action="<?= APP_URL ?>/reporting-officer/generate-report/<?= $fair['id'] ?>" class="d-inline">
        <?= csrfField() ?>
        <button type="submit" class="btn btn-primary btn-sm">
            <i class="bi bi-arrow-clockwise me-1"></i>Regenerate Report
        </button>
    </form>
    <button onclick="window.print()" class="btn btn-outline-dark btn-sm ms-auto">
        <i class="bi bi-printer me-1"></i>Print Report
    </button>
</div>

<!-- Report Header -->
<div class="card border-0 shadow-sm mb-4">
    <div class="card-header bg-dark text-white text-center py-3">
        <h5 class="mb-1 fw-bold">JOB FAIR REPORT</h5>
        <p class="mb-0 small opacity-75">Generated by Reporting Officer</p>
    </div>
    <div class="card-body">
        <div class="row g-3">
            <div class="col-md-6">
                <div class="small text-muted">Job Fair Title</div>
                <div class="fw-bold"><?= htmlspecialchars($fair['title'], ENT_QUOTES) ?></div>
            </div>
            <div class="col-md-3">
                <div class="small text-muted">Date</div>
                <div class="fw-bold"><?= !empty($fair['requested_date']) ? date('F d, Y', strtotime($fair['requested_date'])) : '—' ?></div>
            </div>
            <div class="col-md-3">
                <div class="small text-muted">Venue</div>
                <div class="fw-bold"><?= htmlspecialchars($fair['venue'] ?? '—', ENT_QUOTES) ?></div>
            </div>
        </div>
    </div>
</div>

<!-- Summary Stats -->
<div class="row g-3 mb-4">
    <?php
    $cards = [
        ['Applicants Participated', $summary['total_applicants'],  'secondary', 'bi-people'],
        ['Validated',               $summary['total_validated'],   'info',      'bi-patch-check-fill'],
        ['Interviewed',             $summary['total_interviewed'], 'warning',   'bi-camera-video-fill'],
        ['Hired',                   $summary['total_hired'],       'success',   'bi-person-check-fill'],
        ['Not Hired',               $summary['total_not_hired'],   'danger',    'bi-person-x-fill'],
        ['Agencies',                $summary['total_agencies'],    'primary',   'bi-building'],
        ['Vacancies Offered',       $summary['total_vacancies'],   'primary',   'bi-briefcase-fill'],
        ['Employment Rate',         $summary['employment_rate'].'%','success',  'bi-graph-up-arrow'],
    ];
    foreach ($cards as [$label, $val, $color, $icon]): ?>
    <div class="col-6 col-sm-3">
        <div class="card border-0 shadow-sm text-center py-3 h-100">
            <div class="fw-bold" style="font-size:1.8rem;color:var(--bs-<?= $color ?>);"><?= $val ?></div>
            <div class="small text-muted mt-1"><?= $label ?></div>
        </div>
    </div>
    <?php endforeach; ?>
</div>

<!-- Agency Performance Table -->
<div class="card border-0 shadow-sm mb-4">
    <div class="card-header bg-white py-3">
        <h6 class="mb-0 fw-bold"><i class="bi bi-building me-2 text-primary"></i>Agency Performance</h6>
    </div>
    <div class="table-responsive">
        <table class="table table-sm table-bordered align-middle mb-0">
            <thead class="table-dark">
                <tr>
                    <th>#</th>
                    <th>Agency / Company</th>
                    <th class="text-center">Vacancies</th>
                    <th class="text-center">Total Slots</th>
                    <th class="text-center">Interviewed</th>
                    <th class="text-center">Hired</th>
                    <th class="text-center">Not Hired</th>
                    <th class="text-center">Hire Rate</th>
                </tr>
            </thead>
            <tbody>
            <?php if (empty($agencies)): ?>
                <tr><td colspan="8" class="text-center py-3 text-muted">No agencies yet.</td></tr>
            <?php else: ?>
            <?php foreach ($agencies as $i => $ag):
                $rate = $ag['interviewed_count'] > 0
                    ? round(($ag['hired_count'] / $ag['interviewed_count']) * 100, 0) : 0;
            ?>
            <tr>
                <td class="text-muted"><?= $i + 1 ?></td>
                <td class="fw-semibold"><?= htmlspecialchars($ag['agency_name'], ENT_QUOTES) ?></td>
                <td class="text-center"><?= $ag['vacancy_count'] ?></td>
                <td class="text-center"><?= $ag['total_slots'] ?? 0 ?></td>
                <td class="text-center"><span class="badge bg-info text-dark"><?= $ag['interviewed_count'] ?></span></td>
                <td class="text-center"><span class="badge bg-success"><?= $ag['hired_count'] ?></span></td>
                <td class="text-center"><span class="badge bg-danger"><?= $ag['not_hired_count'] ?></span></td>
                <td class="text-center">
                    <span class="badge bg-<?= $rate >= 50 ? 'success' : 'warning' ?> text-dark"><?= $rate ?>%</span>
                </td>
            </tr>
            <?php endforeach; ?>
            <?php endif; ?>
            </tbody>
        </table>
    </div>
</div>

<!-- Applicant Participation Table -->
<div class="card border-0 shadow-sm">
    <div class="card-header bg-white py-3 d-flex justify-content-between align-items-center">
        <h6 class="mb-0 fw-bold"><i class="bi bi-person-lines-fill me-2 text-success"></i>Applicant Participation (<?= count($applicants) ?>)</h6>
    </div>
    <div class="table-responsive">
        <table class="table table-sm table-bordered align-middle mb-0">
            <thead class="table-dark">
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Preferred Position</th>
                    <th class="text-center">Validated</th>
                    <th>Interviewed By</th>
                    <th class="text-center">Interview Status</th>
                    <th class="text-center">Outcome</th>
                    <th>Remarks</th>
                    <th class="no-print">Action</th>
                </tr>
            </thead>
            <tbody>
            <?php if (empty($applicants)): ?>
                <tr><td colspan="10" class="text-center py-4 text-muted">No applicant records yet.</td></tr>
            <?php else: ?>
            <?php foreach ($applicants as $i => $ap):
                $vsColors = ['approved'=>'success','pending'=>'warning','rejected'=>'danger','not_submitted'=>'secondary','resubmit'=>'info'];
                $vsColor  = $vsColors[$ap['validation_status']] ?? 'secondary';
                $oColors  = ['hired'=>'success','not_hired'=>'danger','for_consideration'=>'info','pending'=>'warning'];
                $oColor   = $oColors[$ap['hiring_outcome'] ?? 'pending'] ?? 'secondary';
            ?>
            <tr>
                <td class="text-muted"><?= $i + 1 ?></td>
                <td class="fw-semibold small">
                    <?= htmlspecialchars(strtoupper($ap['surname']) . ', ' . $ap['firstname'], ENT_QUOTES) ?>
                </td>
                <td class="small text-muted"><?= htmlspecialchars($ap['email'] ?? '—', ENT_QUOTES) ?></td>
                <td class="small"><?= htmlspecialchars($ap['preferred_occupation'] ?? '—', ENT_QUOTES) ?></td>
                <td class="text-center">
                    <span class="badge bg-<?= $vsColor ?>"><?= ucfirst($ap['validation_status']) ?></span>
                </td>
                <td class="small"><?= htmlspecialchars($ap['interviewed_by'] ?? '—', ENT_QUOTES) ?></td>
                <td class="text-center">
                    <?php if ($ap['interview_status']): ?>
                    <span class="badge bg-<?= $ap['interview_status'] === 'completed' ? 'success' : 'warning' ?>">
                        <?= ucfirst($ap['interview_status']) ?>
                    </span>
                    <?php else: ?>
                    <span class="text-muted small">—</span>
                    <?php endif; ?>
                </td>
                <td class="text-center">
                    <?php if ($ap['interview_id']): ?>
                    <span class="badge bg-<?= $oColor ?>">
                        <?= ucfirst(str_replace('_', ' ', $ap['hiring_outcome'] ?? 'pending')) ?>
                    </span>
                    <?php else: ?>
                    <span class="text-muted small">—</span>
                    <?php endif; ?>
                </td>
                <td class="small text-muted">
                    <?= htmlspecialchars(substr($ap['overall_remarks'] ?? '', 0, 40), ENT_QUOTES) ?>
                    <?= strlen($ap['overall_remarks'] ?? '') > 40 ? '...' : '' ?>
                </td>
                <td class="no-print">
                    <?php if ($ap['interview_id']): ?>
                    <a href="<?= APP_URL ?>/reporting-officer/interview/<?= $ap['interview_id'] ?>"
                       class="btn btn-xs btn-outline-primary" style="padding:2px 8px;font-size:.72rem;">
                        <i class="bi bi-eye"></i>
                    </a>
                    <?php endif; ?>
                </td>
            </tr>
            <?php endforeach; ?>
            <?php endif; ?>
            </tbody>
        </table>
    </div>
</div>

<?php $content = ob_get_clean(); include VIEW_PATH . '/layouts/main.php'; ?>
