<?php $pageTitle = $pageTitle ?? 'Job Fair Reports Repository'; ?>
<?php ob_start(); ?>

<?php if ($success): ?>
<div class="alert alert-success alert-dismissible fade show">
    <?= htmlspecialchars($success, ENT_QUOTES) ?>
    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
</div>
<?php endif; ?>

<!-- Filters -->
<div class="card border-0 shadow-sm mb-3">
    <div class="card-body py-2">
        <form method="GET" class="row g-2 align-items-end">
            <div class="col-md-5">
                <input type="text" name="search" class="form-control form-control-sm"
                       placeholder="Search job fair title..."
                       value="<?= htmlspecialchars($_GET['search'] ?? '', ENT_QUOTES) ?>">
            </div>
            <div class="col-md-3">
                <select name="status" class="form-select form-select-sm">
                    <option value="">All Statuses</option>
                    <option value="draft"     <?= ($_GET['status'] ?? '') === 'draft'     ? 'selected' : '' ?>>Draft</option>
                    <option value="submitted" <?= ($_GET['status'] ?? '') === 'submitted' ? 'selected' : '' ?>>Submitted</option>
                    <option value="reviewed"  <?= ($_GET['status'] ?? '') === 'reviewed'  ? 'selected' : '' ?>>Reviewed</option>
                </select>
            </div>
            <div class="col-auto">
                <button type="submit" class="btn btn-primary btn-sm">
                    <i class="bi bi-search me-1"></i>Filter
                </button>
            </div>
        </form>
    </div>
</div>

<div class="card border-0 shadow-sm">
    <div class="card-header bg-white py-3 d-flex justify-content-between align-items-center">
        <h6 class="mb-0 fw-bold">
            <i class="bi bi-archive me-2 text-primary"></i>Reports (<?= count($reports) ?>)
        </h6>
    </div>
    <div class="table-responsive">
        <table class="table table-hover align-middle mb-0">
            <thead class="table-light">
                <tr>
                    <th>Job Fair</th>
                    <th>Fair Date</th>
                    <th>Generated By</th>
                    <th>Generated</th>
                    <th>Submitted</th>
                    <th class="text-center">Status</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
            <?php if (empty($reports)): ?>
                <tr>
                    <td colspan="7" class="text-center py-5 text-muted">
                        <i class="bi bi-archive display-4 d-block mb-2 opacity-50"></i>
                        No reports yet. Generate a report from the Job Fair Report page.
                    </td>
                </tr>
            <?php else: ?>
            <?php foreach ($reports as $r):
                $sColors = ['draft'=>'secondary','submitted'=>'primary','reviewed'=>'success'];
                $sColor  = $sColors[$r['report_status']] ?? 'secondary';
            ?>
            <tr>
                <td class="fw-semibold small"><?= htmlspecialchars($r['fair_title'], ENT_QUOTES) ?></td>
                <td class="small text-muted">
                    <?= !empty($r['requested_date']) ? date('M d, Y', strtotime($r['requested_date'])) : '—' ?>
                </td>
                <td class="small"><?= htmlspecialchars($r['generated_by_name'] ?? '—', ENT_QUOTES) ?></td>
                <td class="small text-muted"><?= date('M d, Y', strtotime($r['generated_at'])) ?></td>
                <td class="small text-muted">
                    <?= !empty($r['submitted_at']) ? date('M d, Y', strtotime($r['submitted_at'])) : '—' ?>
                </td>
                <td class="text-center">
                    <span class="badge bg-<?= $sColor ?>"><?= ucfirst($r['report_status']) ?></span>
                </td>
                <td>
                    <div class="d-flex gap-1">
                        <a href="<?= APP_URL ?>/reporting-officer/reports/<?= $r['id'] ?>/view"
                           class="btn btn-sm btn-outline-primary" title="View">
                            <i class="bi bi-eye"></i>
                        </a>
                        <?php if ($r['report_status'] === 'draft'): ?>
                        <button type="button"
                                class="btn btn-sm btn-primary"
                                title="Submit to Supervising Labor"
                                data-bs-toggle="modal"
                                data-bs-target="#submitModal"
                                data-reportid="<?= $r['id'] ?>"
                                data-fairtitle="<?= htmlspecialchars($r['fair_title'], ENT_QUOTES) ?>"
                                data-remarks="<?= htmlspecialchars($r['overall_remarks'] ?? '', ENT_QUOTES) ?>">
                            <i class="bi bi-send"></i>
                        </button>
                        <?php endif; ?>
                    </div>
                </td>
            </tr>
            <?php endforeach; ?>
            <?php endif; ?>
            </tbody>
        </table>
    </div>
</div>

<!-- Submit to SL Modal (requires remarks) -->
<div class="modal fade" id="submitModal" tabindex="-1" data-bs-backdrop="static">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header bg-primary text-white">
                <h5 class="modal-title fw-bold">
                    <i class="bi bi-send me-2"></i>Submit Report to Supervising Labor
                </h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button>
            </div>
            <form method="POST" action="" id="submitForm">
                <?= csrfField() ?>
                <div class="modal-body">
                    <div class="alert alert-primary d-flex gap-3 mb-3 py-2">
                        <i class="bi bi-file-earmark-bar-graph fs-4 flex-shrink-0 mt-1"></i>
                        <div class="small">
                            <strong id="modalFairTitle"></strong><br>
                            <span class="text-muted">Once submitted, this report will be locked and visible to Supervising Labor.</span>
                        </div>
                    </div>

                    <div class="mb-3">
                        <label class="form-label fw-bold">
                            Overall Remarks <span class="text-danger">*</span>
                        </label>
                        <textarea name="submission_remarks"
                                  id="modalRemarks"
                                  class="form-control" rows="5"
                                  placeholder="Enter your overall assessment of the job fair outcomes, key observations, and recommendations before submitting to Supervising Labor..."
                                  required minlength="10"></textarea>
                        <div class="form-text text-muted">
                            <i class="bi bi-info-circle me-1"></i>
                            Required — minimum 10 characters. These remarks will be permanently saved and visible to Supervising Labor alongside the report.
                        </div>
                    </div>
                    <div class="mb-3">
                        <label class="form-label fw-semibold small">Observations <span class="text-muted">(optional)</span></label>
                        <textarea name="submission_observations" class="form-control form-control-sm" rows="2"
                                  placeholder="Key observations from the job fair..."></textarea>
                    </div>
                    <div class="mb-0">
                        <label class="form-label fw-semibold small">Recommendations <span class="text-muted">(optional)</span></label>
                        <textarea name="submission_recommendations" class="form-control form-control-sm" rows="2"
                                  placeholder="Suggestions for future improvements..."></textarea>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary fw-semibold px-4" id="modalSubmitBtn" disabled>
                        <i class="bi bi-send me-2"></i>Submit to Supervising Labor
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
const submitModal = document.getElementById('submitModal');
if (submitModal) {
    submitModal.addEventListener('show.bs.modal', function(e) {
        const btn = e.relatedTarget;
        document.getElementById('submitForm').action =
            '<?= APP_URL ?>/reporting-officer/reports/' + btn.dataset.reportid + '/submit';
        document.getElementById('modalFairTitle').textContent = btn.dataset.fairtitle;
        const ta = document.getElementById('modalRemarks');
        ta.value = btn.dataset.remarks || '';
        document.getElementById('modalSubmitBtn').disabled = ta.value.trim().length < 10;
    });

    document.getElementById('modalRemarks')?.addEventListener('input', function() {
        document.getElementById('modalSubmitBtn').disabled = this.value.trim().length < 10;
    });
}
</script>

<?php $content = ob_get_clean(); include VIEW_PATH . '/layouts/main.php'; ?>
