<?php $pageTitle = $pageTitle ?? 'Job Fair Reports Repository'; ?>
<?php ob_start(); ?>

<?php if ($success): ?>
<div class="alert alert-success alert-dismissible fade show">
    <?= htmlspecialchars($success, ENT_QUOTES) ?>
    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
</div>
<?php endif; ?>

<!-- Filters -->
<div class="card border-0 shadow-sm mb-3">
    <div class="card-body py-2">
        <form method="GET" class="row g-2 align-items-end">
            <div class="col-md-5">
                <input type="text" name="search" class="form-control form-control-sm"
                       placeholder="Search job fair title..."
                       value="<?= htmlspecialchars($_GET['search'] ?? '', ENT_QUOTES) ?>">
            </div>
            <div class="col-md-3">
                <select name="status" class="form-select form-select-sm">
                    <option value="">All Statuses</option>
                    <option value="draft"     <?= ($_GET['status'] ?? '') === 'draft'     ? 'selected' : '' ?>>Draft</option>
                    <option value="submitted" <?= ($_GET['status'] ?? '') === 'submitted' ? 'selected' : '' ?>>Submitted</option>
                    <option value="reviewed"  <?= ($_GET['status'] ?? '') === 'reviewed'  ? 'selected' : '' ?>>Reviewed</option>
                </select>
            </div>
            <div class="col-auto">
                <button type="submit" class="btn btn-primary btn-sm">
                    <i class="bi bi-search me-1"></i>Filter
                </button>
            </div>
        </form>
    </div>
</div>

<div class="card border-0 shadow-sm">
    <div class="card-header bg-white py-3 d-flex justify-content-between align-items-center">
        <h6 class="mb-0 fw-bold">
            <i class="bi bi-archive me-2 text-primary"></i>Reports (<?= count($reports) ?>)
        </h6>
    </div>
    <div class="table-responsive">
        <table class="table table-hover align-middle mb-0">
            <thead class="table-light">
                <tr>
                    <th>Job Fair</th>
                    <th>Fair Date</th>
                    <th>Generated By</th>
                    <th>Generated</th>
                    <th>Submitted</th>
                    <th class="text-center">Status</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
            <?php if (empty($reports)): ?>
                <tr>
                    <td colspan="7" class="text-center py-5 text-muted">
                        <i class="bi bi-archive display-4 d-block mb-2 opacity-50"></i>
                        No reports yet. Generate a report from the Job Fair Report page.
                    </td>
                </tr>
            <?php else: ?>
            <?php foreach ($reports as $r):
                $sColors = ['draft'=>'secondary','submitted'=>'primary','reviewed'=>'success'];
                $sColor  = $sColors[$r['report_status']] ?? 'secondary';
            ?>
            <tr>
                <td class="fw-semibold small"><?= htmlspecialchars($r['fair_title'], ENT_QUOTES) ?></td>
                <td class="small text-muted">
                    <?= !empty($r['requested_date']) ? date('M d, Y', strtotime($r['requested_date'])) : '—' ?>
                </td>
                <td class="small"><?= htmlspecialchars($r['generated_by_name'] ?? '—', ENT_QUOTES) ?></td>
                <td class="small text-muted"><?= date('M d, Y', strtotime($r['generated_at'])) ?></td>
                <td class="small text-muted">
                    <?= !empty($r['submitted_at']) ? date('M d, Y', strtotime($r['submitted_at'])) : '—' ?>
                </td>
                <td class="text-center">
                    <span class="badge bg-<?= $sColor ?>"><?= ucfirst($r['report_status']) ?></span>
                </td>
                <td>
                    <div class="d-flex gap-1">
                        <a href="<?= APP_URL ?>/reporting-officer/reports/<?= $r['id'] ?>/view"
                           class="btn btn-sm btn-outline-primary" title="View">
                            <i class="bi bi-eye"></i>
                        </a>
                        <?php if ($r['report_status'] === 'draft'): ?>
                        <form method="POST" action="<?= APP_URL ?>/reporting-officer/reports/<?= $r['id'] ?>/submit" class="d-inline">
                            <?= csrfField() ?>
                            <button type="submit" class="btn btn-sm btn-primary" title="Submit to SL"
                                    onclick="return confirm('Submit this report to Supervising Labor?')">
                                <i class="bi bi-send"></i>
                            </button>
                        </form>
                        <?php endif; ?>
                    </div>
                </td>
            </tr>
            <?php endforeach; ?>
            <?php endif; ?>
            </tbody>
        </table>
    </div>
</div>

<?php $content = ob_get_clean(); include VIEW_PATH . '/layouts/main.php'; ?>
