-- Migration 017: Reporting Officer role + hiring outcome tracking

-- 1. Add reporting_officer to users role ENUM
ALTER TABLE users MODIFY COLUMN role ENUM(
    'admin',
    'supervising_labor',
    'barangay_captain',
    'secretary',
    'agency',
    'applicant',
    'techvoc_supervisor',
    'bedo',
    'validating_officer',
    'reporting_officer'
) NULL;

-- 2. Add hiring outcome to interviews table
ALTER TABLE interviews
    ADD COLUMN IF NOT EXISTS hiring_outcome
        ENUM('pending','hired','not_hired','for_consideration') DEFAULT 'pending'
        AFTER overall_remarks,
    ADD COLUMN IF NOT EXISTS hiring_remarks TEXT NULL AFTER hiring_outcome,
    ADD COLUMN IF NOT EXISTS reported_at    TIMESTAMP NULL AFTER hiring_remarks,
    ADD COLUMN IF NOT EXISTS reported_by    INT UNSIGNED NULL AFTER reported_at;

-- 3. Job fair summary reports (generated by reporting officer)
CREATE TABLE IF NOT EXISTS job_fair_reports (
    id                      INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    job_fair_request_id     INT UNSIGNED NOT NULL,
    generated_by            INT UNSIGNED NOT NULL,
    total_applicants        INT UNSIGNED DEFAULT 0,
    total_validated         INT UNSIGNED DEFAULT 0,
    total_interviewed       INT UNSIGNED DEFAULT 0,
    total_hired             INT UNSIGNED DEFAULT 0,
    total_not_hired         INT UNSIGNED DEFAULT 0,
    total_agencies          INT UNSIGNED DEFAULT 0,
    total_vacancies         INT UNSIGNED DEFAULT 0,
    employment_rate         DECIMAL(5,2) DEFAULT 0.00,
    notes                   TEXT NULL,
    generated_at            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (job_fair_request_id) REFERENCES job_fair_requests(id) ON DELETE CASCADE,
    FOREIGN KEY (generated_by)        REFERENCES users(id) ON DELETE RESTRICT,
    INDEX idx_report_fair (job_fair_request_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
